### ISSUE TITLE
Adopter Foster Dashboard: update landing page

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1022]
Please update the view at `/adopter_fosterer/dashboard` per the design below

![Image](https://github.com/user-attachments/assets/7e3b0bcf-5c9e-4e12-8a35-354e402132db)

Design assets can be obtained at: https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=1669-976&t=VTEQx7LaODp1GSzu-1

In this case, we don't need to add a header with breadcrumbs. Please make sure the header is the same size as what we use for `/adopter_fosterer/donations`

**Comment by wandergithub** [comment]
I can work on this.

**Comment by kasugaijin** [comment]
@wandergithub awesome! Generally I like to keep one assignment at a time just so everyone can get something. So once you have finished your currently assigned issue on the dates, feel free to circle back here!

**Comment by coalest** [comment]
@kasugaijin Does this design need to be updated since there will only be species-specific links after #1070 is merged?

Maybe instead of the "Browse All Pets" link it could be two links: "Browse All Cats" and "Browse All Dogs"?

**Comment by kasugaijin** [comment]
Yes you're right @coalest !
If this PR https://github.com/rubyforgood/homeward-tails/pull/1070 is merged when someone starts working on this, then please make sure you show the species speficis buttons (see the Org root Hero section which also will show both). Otherwise, if not merged, please just stick to the single button to `/adoptable_pets` without a species filter

**Comment by kasugaijin** [comment]
@wandergithub this is free if you're still interested :)

**Comment by wandergithub** [comment]
I can take it.
