### ISSUE TITLE
Adopter Fosterer Dashboard: add fostered pets resource

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1023]
If you log in as an adopter and go to the dashboard and click on adopted pets, you will see the adopted pets, and you can then click on two tabs to show the files and incomplete tasks. 

We need to copy this implementation for fosterers, so they can do the same for their fostered pets. The fosterer should be able to go to their dashboard, see a link that says 'Fosters', click it, and see tiles for each dog currently in foster, and then click a tile to see that dog's files and incomplete tasks. This link should not be visible to users that are adopters only.

For reference, this is for pets with a`Match` where the `person_id` matches that of the fosterer user, and the `Match` has a `match_type` of `foster` and it is a `current` match.

Implementation suggestions
- a new Organizations::AdopterFosterer::FosteredPetsController and route to render the correct collection of fostered pets
- re-use the same policy
- re-use the same resources and implementation of these resources as the adopted pets flow
- if you see opportunities to reduce duplication in the view, feel free to make shared partials that can live in `Organizations::AdopterFosterer::Shared`

**Comment by kasugaijin** [comment]
@sarvaiyanidhi FYI this issue is up and very similar to what you just worked on, if you are interested :)

**Comment by sarvaiyanidhi** [comment]
Sure @kasugaijin I would love to work on it.. Can you please assign it to me?

**Comment by kasugaijin** [comment]
@sarvaiyanidhi all yours!
