### ISSUE TITLE
Replace StaffAccount

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/homeward-tails#1034]
We replaced AdopterFosterAccount with the introduction of the Person model. We need to remove StaffAccount as well. The main difference will probably be the `deactivated_at` logic having to be moved. Most likely belongs in `User` with other authz stuff.

**Comment by kasugaijin** [comment]
@mononoken I think it's safe to build off this PR https://github.com/rubyforgood/pet-rescue/pull/997 - it's pretty much done, I just have a question on idexes for Alisa.

**Comment by mononoken** [comment]
Whoops that would have been a good idea! @kasugaijin 🫣
