### ISSUE TITLE
Clicking pet when viewing adoption applications as adopter fosterer leads to unauthorized error

### ISSUE THREAD

**Issue by coalest** [rubyforgood/homeward-tails#1056]
### Reproduction steps:
1. Log in as an adopter, eg. `adopter1@alta.com:123456`
2. Go to the `Adoption Applications`page
3. Click on a pet's name.
4. See the error message like screenshot below:
![Screenshot from 2024-10-10 20-27-17](https://github.com/user-attachments/assets/4bfbf45a-0400-4dd3-abb4-65e47de3b71f)

### Expected behavior:
In theory I have already put in an application to adopt these pets, so I would expect to be directed to a page with information about that pet (either generic information or information on the application I made).

### Actual behavior:
I see an error message flash that says "You are not authorized to perform this action."
In the logs, I see a request was sent to `GET /alta/adoptable_pets/1` failed the policy check and resulted in a 302 redirect.
I believe because [this part of the expression](https://github.com/rubyforgood/pet-rescue/blob/main/app/policies/organizations/adoptable_pet_policy.rb#L11) returns `false` as the pet does have a match (the current user).

**Comment by princekumarg12** [comment]
Hi,
I would like to take on the task regarding the authorization issue with the adoption application page. I believe I can help identify and resolve the underlying policy check problem.

Please let me know if I can be assigned to this task.

**Comment by kasugaijin** [comment]
@princekumarg12 all yours!

**Comment by princekumarg12** [comment]
@kasugaijin i found this while debugging

There are two reasons for this bug:

1. user.staff_account is nil, which causes authorization to be denied.
See the screenshot for reference.
![Screenshot from 2024-10-13 00-28-54](https://github.com/user-attachments/assets/95119c04-0f7d-41f9-8a31-b4f7e8117825)

2. The user does not have permission to "manage_pets."

**Comment by kasugaijin** [comment]
Ah good catch! So we have this PR https://github.com/rubyforgood/pet-rescue/pull/1039 to remove the StaffAccoubt model. Can you please check out that branch and see if the bug is fixed? It might not need fixing in that case.

**Comment by princekumarg12** [comment]
I checked out the branch 1034-replace-staffaccount and found that the issue still persists.

**Comment by kasugaijin** [comment]
Ah ok thank you! I think it would make sense to hang on until that branch https://github.com/rubyforgood/pet-rescue/pull/1039 is merged because we are changing the architecture around a bit, and I think that would impact this fix.

**Comment by kasugaijin** [comment]
FYI @princekumarg12 that branch mentioned above is now merged. Are you interested in pursuing this now?

**Comment by jmilljr24** [comment]
I don't think we need to change anything with authorization on this. Once a pet is adopted, the show page for this pet is not longer accessible for any adopter. For staff it simply displays a link to manage.

We can either disable the link for the adopter, or have it link to "adopted pets" page for that specific user when the status is adoption made. We would need to disable the link for an adopter if they applied to adopt the pet but someone else adopted it.
![Screenshot from 2024-11-28 07-38-43](https://github.com/user-attachments/assets/0afcc8a9-29e8-4e07-a58a-6445e0a07112)

Thoughts @kasugaijin @mononoken ?

**Comment by kasugaijin** [comment]
I like the idea of disabling the link for adopted pets. This should work fine 99% of the time. There might be the edge where someone has their adoption applications page open when the pet becomes adopted and that link will still try to go to the pet show page...but let's see how many times that actually happens.

**Comment by kasugaijin** [comment]
@fivefootbot all yours
