### ISSUE TITLE
Staff: Dashboard index summary stats visual design improvement

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1057]
This is not urgent, but if someone has an eye for design and wants to tackle this - please provide ideas below
We have these sumamry stats on the staff dashboard index for pet tasks, adoption applications, and fosters, but I do not like the large purple text. I think it could be refined, with a different colour and perhaps and icon is the clickable link (I am open to ideas).

![image](https://github.com/user-attachments/assets/282facce-2685-4ebc-84f4-bf1f5294db6d)

Please base any design ideas on our theme, which is found here (look around these theme pages and see if there are elements or designs we can use) https://geeksui.codescandy.com/

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin ,

Was just playing around trying to come up with some suggestion... Let me know if you like below option for stats

![staff_dashboard](https://github.com/user-attachments/assets/6cd0e916-dbce-40e2-95b5-746551aa2b20)

**Comment by kasugaijin** [comment]
@sarvaiyanidhi thanks for taking a look! I definitely think that’s better. One opinion, I think we could make the two stats for fosters the same colours as for applications, purple and orange. Otherwise it feels like a lot of different colours. Thoughts ?

**Comment by sarvaiyanidhi** [comment]
Sure, let me play around with couple of more options and post design for reference.

**Comment by sarvaiyanidhi** [comment]
Few options let me know if you like any one of it

Option 1

![staff_dashboard_option_1](https://github.com/user-attachments/assets/ab8d8496-0031-42cc-a6ad-5629788e1c46)

Option 2

![staff_dashboard_option_2](https://github.com/user-attachments/assets/9fa924f4-17b2-4014-80f6-ec297f295ea3)


Option 3

![staff_dashboard_option_3](https://github.com/user-attachments/assets/0cbf41de-7e6a-479f-b6a0-40731a4b479a)

**Comment by kasugaijin** [comment]
@sarvaiyanidhi I prefer option 2! Thank you for these
