### ISSUE TITLE
Feedback Form: Add topic dropdown and explanation of how to report a bug fix

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1058]
On this feedback page, please add a required select called Subject, that has values: General feedback, Feature request, Bug. Whatever is selected should then become the title of the email sent to the developers via the Mailer.

I think it would also be good to add a link 'How to submit a bug or feature request' above the Message label. When clicked, we use a turbo frame to load the response above the message label. We can use the Feedback Controller #show for this. Now, I **think** placing a turbo frame within a form should work fine, as long as it's a sub-section of the form. If this does not work, you can place this frame/link outside the form, just under the description `Found a bug? Want to request a feature? Contact our dev team with the form below.`

The content rendered in the frame should be a card with the following text (you can refine this text - ask GPT for something better perhaps! But keep it brief):

**Reporting Bugs**
Provide as much detail as possible including:
- the organization name
- the url of the page the bug was found
- the steps that led to the bug
- your expected outcomes versus what you experienced

**Requesting Features**
Provide as much detail as possible including:
- what page the feature should live
- what the feature should do
- why this feature will be useful

<img width="752" alt="image" src="https://github.com/user-attachments/assets/3b479218-cf8c-482a-96d8-a25afcc73a90">

**Comment by jmilljr24** [comment]
On it. I will finalized after #1051 is merged.

**Comment by jmilljr24** [comment]
I played around with the 'how to' link a bit. I'm not in love with link above the message select but maybe I'm not doing it how you imagined? I also tried adding it below the submit button and I kind of like it better but not sure. Just looking for thoughts/idea.

**Option 1**
![Screenshot from 2024-10-12 17-24-54](https://github.com/user-attachments/assets/f6c75dad-a442-45ae-9454-6f9e75232176)
![Screenshot from 2024-10-12 17-24-40](https://github.com/user-attachments/assets/2dbeaa01-ff30-491e-9305-b0f4b0897855)

**Option 2**
![Screenshot from 2024-10-14 14-58-39](https://github.com/user-attachments/assets/278c3a94-4553-4d8e-8c02-7d3df7f297e4)
![Screenshot from 2024-10-14 14-58-49](https://github.com/user-attachments/assets/81097609-05c9-401b-9756-4f80100b211a)

**Comment by kasugaijin** [comment]
@jmilljr24 I know you're working on the pet species PR. Are you also planning to work on this one given your steps above? No pressure either way.

**Comment by jmilljr24** [comment]
> @jmilljr24 I know you're working on the pet species PR. Are you also planning to work on this one given your steps above? No pressure either way. I am just doing some issues housekeeping.

@kasugaijin blocked by #1051. I will just need to deal with any merge conflicts and it will be good to go. I can push up a draft if you'd like.

**Comment by kasugaijin** [comment]
Ah yes you're right. I will ping the author to see if I can unblock.
