### ISSUE TITLE
Adoptable Pets: Add species identifier next to pet name

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1061]
Right now, if you go to the `/adoptable_pets` page you will see a load of pets but have no idea what species they are. 
Please add a badge next to the pet name on the index page, and the show page, of the species (dog or cat)

![Image](https://github.com/user-attachments/assets/546d2f35-caa2-415c-96af-4260b5950c86)

Please use this badge
![Image](https://github.com/user-attachments/assets/fcc5ff86-760d-4a1c-ac7a-85eb1a9ce5e5)

See theme badges: https://geeksui.codescandy.com/geeks/docs/badge.html

**Comment by coalest** [comment]
I can take this one :raising_hand:

**Comment by coalest** [comment]
I chose a spacing that I thought looked ok (tailwind: `gap-3`, or `0.75rem`/`16px` in css). Let me know if you think the placement could be improved.

I don't see any `view` tests, so I wasn't sure the recommended way to add a test. Instead I just provided some screenshots.
