### ISSUE TITLE
Adoptable Pets: Add empty state

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1062]
If you go to `/adoptable_pets` and perform a search that returns no results, we don't show anything. 

Please add an empty state and render it if the adoptable pets collection is empty. It should say "We don't have any pets matching your search criteria." 

![Image](https://github.com/user-attachments/assets/319d8b8a-f05c-4b2c-bf35-ffb1faacabbb)

**Comment by Gabe-Torres** [comment]
I'll take this one!

**Comment by kasugaijin** [comment]
FYI @Gabe-Torres this PR https://github.com/rubyforgood/homeward-tails/pull/1070 is creating separate adopatable pet pages, by species, but it's using the same controller. So, the empty state rendering shouldn't be impacted much. But, thought I would let you know. P.S. let me know if you have any questions.

**Comment by kasugaijin** [comment]
@Gabe-Torres how's this going?

**Comment by Gabe-Torres** [comment]
I'll have this pr submitted asap!

**Comment by kasugaijin** [comment]
Thanks @Gabe-Torres no major rush! Just checking in :)

**Comment by Gabe-Torres** [comment]
PR submitted!

**Comment by Gabe-Torres** [comment]
Here is the new new. Sorry for the confusion! 🐶 

This PR has the latest main and no previous commits from my last attempt. 
I will delete the previous branch once this issue is closed.
