### ISSUE TITLE
UI: Non-org root page - Fix button contrast on hover

### ISSUE THREAD

**Issue by Kritika745** [rubyforgood/homeward-tails#1063]
Visit the root home page. At the bottom there is a button/link "learn more about ruby for good". When hovering over the button, the text is difficult to read. Fix the contrast of the button/text on hover. Preferably using bootstrap and [geekui](https://geeksui.codescandy.com/geeks/docs/buttons.html).

![Screenshot from 2024-11-28 08-09-52](https://github.com/user-attachments/assets/25b844a3-87cd-4858-aec5-c56dec641d9a)

**FIX**
![Screenshot 2024-10-17 092427](https://github.com/user-attachments/assets/d1855176-911d-4928-a45f-6363b2cac117)

**Comment by kasugaijin** [comment]
@Kritika745 thank you. All yours!

**Comment by Kritika745** [comment]
Okay. I'll do it

**Comment by coalest** [comment]
@Kritika745 FYI This repo has the `hacktoberfest` topic attached, so any PR that gets merged will count towards Hacktoberfest (even if it doesn't have the Hacktoberfest label). I completed Hacktoberfest by accident this way.

**Comment by atbalaji** [comment]
I would like to work on this. Also is it okay if I text color is white instead of current color. It will solve the contrast problem

**Comment by kasugaijin** [comment]
All yours @atbalaji id rather I’f we can keep the theme buttons so please check those and see if something works from there before introducing any custom classes or css! https://geeksui.codescandy.com/geeks/docs/buttons.html

Go to their docs > components to see the buttons
