### ISSUE TITLE
Org Root Page: Update the CTA link to use the primary button

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1071]
If you go to an org home page and scroll down you will see a call to action card with a link to become an adopter now! This link should use the `btn btn-primary` classes so it looks like this button, and it should say 'Sign Up'
<img width="261" alt="image" src="https://github.com/user-attachments/assets/d91cf84f-6e47-4d53-af21-dfb94c664f60">

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/26e3b34f-3437-46cd-a09e-9c1bcfcbd4dd">

**Comment by Yuji3000** [comment]
I'd like to take this one

**Comment by kasugaijin** [comment]
@Yuji3000 all yours

**Comment by Yuji3000** [comment]
@kasugaijin Got it!
