### ISSUE TITLE
Staff Dashbord: Make filter UI consistent

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1082]
Log in as staff and compare the filter UI for /pets and /default_pet_tasks and you will note some improvements could be made

Default pet tasks - the filter select widths are wider than necessary, causing the filter to span two rows. Make these narrower so the filter spans one row on a normal screen width e.g. 1920 px.
![Image](https://github.com/user-attachments/assets/0332443b-01fb-4cf6-8a7e-dc563e628261)

Pets filter - the filter is not contained within a card like the other filters, and the buttons are to the right. Update this filter so it looks like the others (in a card, buttons below).
![Image](https://github.com/user-attachments/assets/c614fd85-3d5c-4d2a-9434-b8e52c744f73)

**Comment by MichaScant** [comment]
Hi @kasugaijin, can I be assigned this issue?

**Comment by kasugaijin** [comment]
@MichaScant all yours

**Comment by MichaScant** [comment]
thank you!
