### ISSUE TITLE
Default Pet Tasks: Add mobile friendly cards

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1083]
Log in as staff and go to /default_pet_tasks in a mobile view and you will see the tasks table remains. Now check out /pet or /adopter_applications and you will see we show cards. 

Implement the same behaviour for default pet tasks. Use the same breakpoints and implementation as the other resources.

**Comment by MichaScant** [comment]
Hey, can I be assigned this issue, please?

**Comment by kasugaijin** [comment]
@MichaScant how's this going?

**Comment by MichaScant** [comment]
Hi, sorry, ill push a pr for this issue tomorrow, its almost done for the most part, I just got delayed due to personal problems and interviews

**Comment by kasugaijin** [comment]
@MichaScant no problem at all! Just checking in. Good luck on the interviews.

**Comment by MichaScant** [comment]
Hey @kasugaijin would these card designs work?

<img width="340" alt="Screenshot 2024-11-13 at 6 48 28 PM" src="https://github.com/user-attachments/assets/7b2ab545-ee76-48c4-b086-7a0fea72b758">

**Comment by MichaScant** [comment]
if so let me know please and ill create the pr, thank you!

**Comment by kasugaijin** [comment]
@MichaScant yes that card looks good!
