### ISSUE TITLE
Fosterer Invites: Enable staff to enter fosterer phone number and address when inviting

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1084]
This is a bit more of a complex project. It's not too hard, but involves a bit of nuance. Hopefully my notes are useful, but ask if you have any questions.

Currently, staff can only invite a fosterer with a first name, last name and email. This is because invitations are done on `User` and we reserve the `User` model for authentication and authorization only, so do not store other personal data on it. Instead, we use an associated `Person` model to hold first and last name, email and phone number (and whatever else we need in the future). We also store addresses in a `Location` model.

Invites on the `User` model are handled by the `Organizations::Staff::InvitationsController`. The limitation of the implementation is that we are confined to a single invitation resource to handle inviting staff, and fosterers, so it's an ugly controller. It will do for now, though. 

Desired Outcome
**We need to enable staff to enter all of the relevant data for a fosterer once, when they invite them. This includes email, first name, last name, phone number and location attributes.**

My thoughts are:
- we can add these new fields to the fosterer invitation form (phone, and location attributes)
- then in `Organizations::Staff::InvitationsController` when we create the `User`, we then update its `Person` with the phone number (note that a Person gets created in [this callback](https://github.com/rubyforgood/homeward-tails/blob/64e94fd969a77cb0f85e66b1ec9c4e0f4aa6f29d/app/models/user.rb#L72) when a user is created)
- then create the person's associated location record
- we should just need to permit these params and they should be available to use
- If all these records persist, then we call `invite!`. 

Note, you will need to add a `belongs_to :person` on `Location` and add a migration for a `person_id`, and enable `Person` to accept nested attributes for location. We should not validate `person_id` on `Location`, however, as Locations can exist without a person. We shouldn't need to provide an organization id.

Furthermore, staff currently have the ability to edit a fosterer (`Person`) (see `app/controllers/organizations/staff/fosterers_controller.rb`). Please update this edit form to show, but disable editing, the `email` field. We must not allow editing email, because the Person's email should always match the associated User email (herein lies the issue of storing duplicate data on two models, but is the path we decided for various reasons). Staff should also be able to update location details on this form, so please add these fields.

**Comment by mononoken** [comment]
My understanding

## AC
- [ ] Add phone to fosterer invite form (on Person record)
- [ ] Add location to fosterer invite form (on Person record)
- [ ] Disable email field for fosterer edit

**Comment by mononoken** [comment]
@kasugaijin 
- Do we want to make phone and location required for this form? Or should they be optional?

**Comment by kasugaijin** [comment]
Yes that looks right @mononoken 
I think optional phone and address and required name and email works. Staff should be able to add phone and/or address on the edit firm
