### ISSUE TITLE
Update Sign Up form UI

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1097]
When adopters sign up they see the rather generic looking sign up form. Let's use the Log In layout for the sign up form. 

https://www.loom.com/share/b60ccca98ef84e9581710d6f65064c87?sid=fd281655-ff7f-48bc-b188-24ae7d7eca0c

**Comment by Meri-MG** [comment]
hi, @kasugaijin, can i take this one?

**Comment by kasugaijin** [comment]
@Meri-MG all yours
Sorry PR reviews from me are slow but I will get to stuff on the weekend

**Comment by Meri-MG** [comment]
Hi, @kasugaijin, how will we know if the organization has a logo? since we want to render it conditionally?

**Comment by kasugaijin** [comment]
@Meri-MG we include avatarable module on Organization, so we should be able to check if there is an attached image. We do something similar in the top of the sidenav in the staff dashboard - we either render the org logo or name. Let me know if that doesn't help!

**Comment by Meri-MG** [comment]
sorry, @kasugaijin , just coming back to this, so if i use the logic given in the side bar, we get the result below, the avatar isnt present, so the name of organization is displayed twice if keeping the `h1` title as well. shall i display the tenant name only if the avatar is present?
<img width="564" alt="Screenshot 2024-11-28 at 15 17 55" src="https://github.com/user-attachments/assets/247bf70d-3d8d-48c9-bfda-d9f408719fa8">


```
<div class='d-flex justify-content-center'>
              <div class='d-flex flex-column align-items-center mb-3'>
                <% if Current.organization.avatar.attached? %>
                  <%= image_tag Current.organization.avatar, alt: current_organization_name, title: current_organization_name, class: 'rounded-1' %>
                <% else %>
                  <%= current_organization_name %>
                <% end %>
                <h1 class='text-muted'><%= Current.tenant.name %></h1>
              </div>
            </div>
            <h1 class="mb-1 fw-bold">Sign up</h1>
          </div>
```

**Comment by jmilljr24** [comment]
@Meri-MG Ben may not get back to you right away(life stuff) but for the meantime here is my vote. We definitely only want to display the name once. I think he mentioned the side nav as an example, not that you need to keep it exactly the same. 

I would just remove the 'else'. If avatar attached, display image. Always display the h1 tenant name.
