### ISSUE TITLE
Bug: super admin cannot access /staff/organization/edit

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1098]
Log in as staff and go to the dashboard. In the navbar there should be a Settings link under Admin section. This is not visible, but you can access it by going to `/staff/organization/edit`. 

The issue is in the policy check in `app/views/layouts/dashboard/_sidebar.html.erb` for some reason is returning false so the link does not show.

**Comment by Meri-MG** [comment]
Hello, @kasugaijin, shall i take this one once https://github.com/rubyforgood/homeward-tails/pull/1109 is merged?
