### ISSUE TITLE
Adopter flow: update copy above embedded form

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1099]
If an organization has a third party form URL saved at `/staff/organization/edit` it means that when a new adopter signs up, they will be asked to fill out this form (show in an irframe). We need to inform the user to make sure they use the same email address for the form as they did to sign up for the adopter account.

Please update this note to start with `Please complete this form using the same email address you signed up with. ...`

![Image](https://github.com/user-attachments/assets/098abe7e-6ffe-4846-8bf4-894593c3726a)

Please add a sentence `Please ensure the email you use in the form is the same as the email on your account on this website.`
![Image](https://github.com/user-attachments/assets/2510c1f6-c640-4e5f-914a-e71df9e686e9)

**Comment by wiliajc87** [comment]
Hey @kasugaijin , could I snag this as a first contribution?

**Comment by jmilljr24** [comment]
@wiliajc87 All yours. Let us know if you have any questions.

**Comment by wiliajc87** [comment]
@jmilljr24 I do seem to be running into an error when trying to push my branch:
```
jordy@jordys-MacBook-Pro homeward-tails % git push origin 1099-update-embedded-form-copy
ERROR: Permission to rubyforgood/homeward-tails.git denied to wiliajc87.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm able to push/pull from a repo under my own account, so I'm wondering if there's a permissions issue? My `.git/config` looks like this:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:rubyforgood/homeward-tails.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
	vscode-merge-base = origin/main
[branch "1099-update-embedded-form-copy"]
	vscode-merge-base = origin/main
[snyk "/Users/jordy/Code/homeward-tails"]
	baseBranch = main
```

**Comment by wiliajc87** [comment]
Ah, my bad, missed that instruction--no worries, I've got it

**Comment by wiliajc87** [comment]
PR is here: https://github.com/rubyforgood/homeward-tails/pull/1114
