### ISSUE TITLE
Footer: update links to the legal stuff

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1100]
Go to an organization's site and look at the footer. You will see three links going to the legal stuff. These links do not work. Please update the routes to point where they need to go (see the sign up links, which work)

![Image](https://github.com/user-attachments/assets/bdd7c722-abac-4587-841a-00ce5ca453cd)

**Comment by jrussell416** [comment]
I'd like to take on this issue, please

**Comment by kasugaijin** [comment]
@jrussell416 all yours

**Comment by jrussell416** [comment]
@kasugaijin 
The footer currently uses "Terms of Use," while the signup page uses "Terms and Conditions" for the link text. Should I leave "Terms of Use" as is or change to "Terms and Conditions"?
![Screenshot 2024-10-31 121533](https://github.com/user-attachments/assets/89072b98-0176-47fb-b1f4-ad14fdacbd22)

**Comment by kasugaijin** [comment]
@jrussell416 please update it so it's consistent with the sign up.

**Comment by kasugaijin** [comment]
@jrussell416 how's this going?

**Comment by palidii** [comment]
@kasugaijin If it hasn't been implemented yet, I'm happy to adjust the lines.

**Comment by jrussell416** [comment]
> @jrussell416 how's this going?

Finished implementing the links. I admit I don't have experience with writing tests, so that's what am stuck on.
