### ISSUE TITLE
Prevent editing of emails on User

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1101]
We currently allow users to edit their `User` email address. For example, log in as an adopter and go to dashboard > edit settings, or as staff, go to the dashboard, then top right, click on your avatar > account settings. 

Please disable the email field so people cannot edit it. 

Please also add a model validation on User that prevents changing of the email on `update`

**Comment by MichaScant** [comment]
Hey @kasugaijin can I be assigned this issue?

**Comment by jmilljr24** [comment]
@MichaScant Have at it! Thanks

**Comment by MichaScant** [comment]
Hey, would something like this work for the model validation?

<img width="967" alt="Screenshot 2024-10-30 at 2 39 10 PM" src="https://github.com/user-attachments/assets/79035f40-36d7-41d0-8539-675aac75cfb5">

**Comment by kasugaijin** [comment]
> Hey, would something like this work for the model validation?
> 
> <img alt="Screenshot 2024-10-30 at 2 39 10 PM" width="967" src="https://private-user-images.githubusercontent.com/89426143/381688815-79035f40-36d7-41d0-8539-675aac75cfb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTQxODQsIm5iZiI6MTczMDMxMzg4NCwicGF0aCI6Ii84OTQyNjE0My8zODE2ODg4MTUtNzkwMzVmNDAtMzZkNy00MWQwLTg1MzktNjc1YWFjNzVjZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE4NDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MWFkZjMzOWJlZjhhMjNhZTkxMmNhNWUzOTAzOWUyODNlZTNkOGM0Y2QzYzdlYzVlZjQxNTFlZjMxOWM2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R25Rnbk4dvBZkPVvYdeIEgspJzJhYGCOQWfSvSP39MQ">
> this is an example and the email field will be disabled. If someone tries to change the email on the user they should get this message

the field should be disabled. there should be a disabled attribute for the email input in the bootstrap form. This will make the field look like this and will prevent from a user clicking to focus on the input. Within the disabled field should show the value for their email address when editing user settings. 

<img width="198" alt="image" src="https://github.com/user-attachments/assets/52a4621f-0f48-4fc7-b887-42cd617f4f12">

**Comment by MichaScant** [comment]
Sorry I should clarify that i took out the disabled attribute for Bootstrap just to test if the model validation for the user would prevent the email from updating if there was a change.

This is how the disabled version would look:
<img width="967" alt="Screenshot 2024-10-30 at 2 39 10 PM" src="https://github.com/user-attachments/assets/f8209bf3-4173-46c0-a128-cb8448e1c18c">

**Comment by MichaScant** [comment]
For the message, I added this in the User model which is called on update:

```
  validate :check_email_change, on: :update
  
  def check_email_change
      errors.add(:email, "Email cannot be changed") if (email_changed?)
  end
```
  
 just to ensure there is no way for the user to change the email on update

**Comment by kasugaijin** [comment]
Ah yea thy makes sense. Can you also disable the input as well? A disabled input is ideal so the user knows up front it’s not editable

**Comment by MichaScant** [comment]
yeh the input should be disabled in the second screenshot i sent

'''  <%= f.email_field :email, autofocus: true, autocomplete: "email", disabled: true, class: 'form-control' %> '''

**Comment by kasugaijin** [comment]
> yeh the input should be disabled in the second screenshot i sent, added disabled: true as shown below
> 
> `<%= f.email_field :email, autofocus: true, autocomplete: "email", disabled: true, class: 'form-control' %> `

Yes that looks good!

**Comment by kasugaijin** [comment]
> For the message, I added this in the User model which is called on update:
> 
> ```
>   validate :check_email_change, on: :update
>   
>   def check_email_change
>       errors.add(:email, "Email cannot be changed") if (email_changed?)
>   end
> ```
> 
> just to ensure the user cannot change the email on the update

Can you please add a comment above this method, something like 
# we do not allow updating of email on User because we also store email on Person, and the values should be the same

**Comment by MichaScant** [comment]
ok will do, thank you!
