### ISSUE TITLE
Staff Dashboard: Add pagination to Adopters / Fosterers / Staff

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1105]
On the Staff dashboard, people are listed in their respective page e.g.  `/alta/staff/adopters`. Each table should be limited to 10 people per page. Reference the Staff/Pets page for example. There is no need for a search function at that time.

Add pagination to:

- [ ] Fosterers
- [ ] Adopters
- [ ] Staff

![Screenshot from 2024-10-30 21-00-54](https://github.com/user-attachments/assets/6158838a-4159-4c34-acc4-f7b0cc926542)

**FIX**
![Screenshot from 2024-10-30 08-38-44](https://github.com/user-attachments/assets/3bd8e27a-71e2-4203-88ee-73ecd6effe7a)

**Comment by MichaScant** [comment]
Hey, can I be assigned this issue?

**Comment by jmilljr24** [comment]
@MichaScant Let me know if you have any questions!!
