### ISSUE TITLE
Adopter Dash: Add margin to buttons on 1024px width

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1120]
Log in as an adopter and you will be redirected to your dashbaord landing page. Make the screen width 1024px and you will see the buttons need margin. Please fix.

![image](https://github.com/user-attachments/assets/31e7113d-e2dd-4abd-9810-4ade2e0dcf37)

**Comment by palidii** [comment]
@kasugaijin hey i would like to implement the issue. Can you assign it to me?

**Comment by jmilljr24** [comment]
@palidii Assigned! Thank you

**Comment by palidii** [comment]
@jmilljr24 @kasugaijin Hello, thanks for assigning the issue. I have already implemented it and created a pull request. Feel free to check it and give me feedback. I would be happy to check other similar issues if any are available.
<img width="1040" alt="iPadProSize1024Fix" src="https://github.com/user-attachments/assets/625a2687-dfd9-449c-b30c-b3af9ce555bd">
<img width="568" alt="iPhone14ProMax-Fixx" src="https://github.com/user-attachments/assets/011d3f36-969d-47a5-ae89-94dd2ca76237">
<img width="1122" alt="ResponisveFix1024" src="https://github.com/user-attachments/assets/176843f2-9c49-49aa-9bfb-6769c8a9b1f9">
