### ISSUE TITLE
Finish off this PR - Front End UI

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1121]
This PR https://github.com/rubyforgood/homeward-tails/pull/993/files is close to being done, but needs finishing. To make changes, you will need to pull down the branch locally, then make a PR to merge into the branch (like this one https://github.com/rubyforgood/homeward-tails/pull/1103).

- I don't think there is any value showing the images on mobile, so make them show on desktop view only
- The images should be updated to have borders around each section (e.g., hero and about us) like these (but we don't need the side labels): https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=1709-1001&t=mgMF60fFNTB5wShw-1
- Please run the images you get from Figma through **https://tinypng.com/** to make the file size small
- It would be nice to have a bit more of a gap between the two sections to make it clearer they are separate pages

![image](https://github.com/user-attachments/assets/d0c9f652-8806-4f72-ac03-93ed125630d2)

**Comment by jp524** [comment]
I'd like to help with this!

**Comment by jmilljr24** [comment]
@jp524 Assigned! Thanks
