### ISSUE TITLE
Org Root: add copy to translation file

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1152]
We have a few things on the Org home page `app/views/organizations/home/index.html.erb` that are hard-coded strings. These should be moved to en.yml

**Comment by Isaac3924** [comment]
Could I have this assigned to me?

**Comment by jmilljr24** [comment]
@Isaac3924 All yours!

**Comment by Isaac3924** [comment]
Made a pull request that should resolve this issue! Please let me know if there's further refactroring I need to do, or something I missed!
