### ISSUE TITLE
Organization Account Request

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1160]
A few small UI updates for this page `/organization_account_request/new`
- remove the button on the top right
- Update the header to say 'Are you a Pet Rescue and want an account on Homeward Tails?'
- Update the description to say 'Submit the form below if you are a pet rescue and would like your own customizable website and management platform on Homeward Tails. We'll follow up with you shortly to finalize your request.'

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/3fc40c8e-5868-4f74-9308-23eaedf1ea47">

**Comment by MichaScant** [comment]
Hey, could I be assigned this issue?
