### ISSUE TITLE
Org Root: About Us - Display paragraphs

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1168]
Staff can edit the About Us section on the Org home page at `staff/custom_page/edit`. Paragraphs are not currently displayed when new lines are saved in the form text area. Update the home index page to display paragraphs. Using [simple_format](https://api.rubyonrails.org/v7.2.2/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format) should be enough but if not please investigate alternatives. We could use something like Action Text but that may be overkill for this.

**FIX**
![Screenshot from 2024-11-20 09-09-30](https://github.com/user-attachments/assets/bfd7674b-745d-4884-9b8f-22b77a93e2fd)

**Comment by Aaryanpal** [comment]
@jmilljr24 
Will take this one?

**Comment by jmilljr24** [comment]
@Aaryanpal Assigned. Thanks!
