### ISSUE TITLE
Adoption Application Reviews - Translation missing

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1191]
Translation for "awaiting data" is missing form `en.yml`. Update to resolve error.

To reproduce, visit Adoption Applications on the staff dashboard. Change a application status to "Awaiting Data".
![Screenshot from 2024-11-27 11-20-43](https://github.com/user-attachments/assets/32960c06-004d-4eda-8083-c3189c18e9af)
![Screenshot from 2024-11-27 11-14-17](https://github.com/user-attachments/assets/905ec4fa-7bea-487c-afc4-355d5af85225)

**Comment by Aaryanpal** [comment]
shall i fixed this in the same PR
@jmilljr24 ?

**Comment by jmilljr24** [comment]
@Aaryanpal I think we should just keep things separate. I doubt any issues will come up with either but it makes it easier if it does. Push up the fix for the other and I can then assign this to you if you want.

**Comment by Aaryanpal** [comment]
@jmilljr24 sure.
Let's Keep them separate.
