### ISSUE TITLE
UI Mobile: How to apply for adoption overflow

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1192]
On the Organization home page the steps on how to apply do not wrap. Fix for screen sizes below [Bootstrap medium](https://getbootstrap.com/docs/5.3/layout/breakpoints/#available-breakpoints) < 768px. Size small screens could possibly be displayed 2 by 2 grid. Extra small will need to be vertical. The icon size may make this quite long to scroll through on mobile so feel free to adjust and see what works best.

![Screenshot from 2024-11-27 11-26-36](https://github.com/user-attachments/assets/2b5385cd-208b-4855-bc44-65632836efc0)

**Comment by Aaryanpal** [comment]
@jmilljr24 this too

**Comment by jmilljr24** [comment]
@Aaryanpal have at it!
