### ISSUE TITLE
UI Mobile: Pet task - show completed toggle overflows

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/homeward-tails#1193]
On mobile visit staff dashboard > Pets. View a pet and select the tasks tab. The show completed toggle should not overflow the card. It also might be worth  seeing if stacking the edit/delete buttons vertically on mobile looks good and gives more room for the task text.

![Screenshot from 2024-11-27 11-44-06](https://github.com/user-attachments/assets/a9f59dc8-f611-4498-bdaf-8c8b70556dac)

**Comment by Aaryanpal** [comment]
Starting with this @jmilljr24
