### ISSUE TITLE
Pet attachments: if no file is provided I should be notified when I click attach

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1221]
Log in as staff and go to a pet photos and files tabs. Click attach and you will see a flash that the upload was successful, even if no attachments were provided. Change this to render an alert saying 'Please select a file to attach'.

Please add the logic to this concern `module AttachmentManageable` and call in the appropriate action, ideally in a `before_action` filter. This logic to check there is a file should work as follows when the user clicks the attach button:

- if no attachments provided an, shows the above alert
- if one attachment provided, continues with happy path
- if two attachments provided, continues with happy path

It would be good to add some controller tests for this behaviour.

**Comment by mgrigoriev8109** [comment]
@kasugaijin can I work on this one?

**Comment by kasugaijin** [comment]
@mgrigoriev8109 all yours
