### ISSUE TITLE
Pet attachments: Add copy below the input stating file type and size restrictions

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1222]
Log in as staff and check the Cusom Page route, and you will see we add notes below the inputs to specify file type and size. Add the same to the Pet Files and Pet Attachments tabs. Check `pet.rb` to confirm the file type and size for each. 

Incidentally, please double check the Custom Page hint, because it says `Images must be .png or .jpeg under 2MB` but on the model it looks like images are limited to 1MB. So please update this text on Custom Page accordingly.

**Comment by jasonwang7517** [comment]
@kasugaijin Happy to pick this up as a simple first ticket.

I double-checked the validations on the `custom_page` model and it seems that they can both be under 2 megabytes:
`  validates :hero_image, content_type: ["image/png", "image/jpeg"],
    limit: {max: 1},
    size: {less_than: 2.megabytes}

  validates :about_us_images, content_type: ["image/png", "image/jpeg"],
    limit: {max: 2},
    size: {less_than: 2.megabytes}`

So I think the original copy is good.

**Comment by kasugaijin** [comment]
All yours @jasonwang7517

**Comment by jasonwang7517** [comment]
Sorry, very new to the open-source paradigm here.

Do I have to get added as a collaborator to be able to contribute to the repo? Getting a 403 error when I'm trying to push up my feature branch.

**Comment by kasugaijin** [comment]
@jasonwang7517 you need to fork the repo and make a pull request on the fork (see readme) :)

**Comment by jasonwang7517** [comment]
> @jasonwang7517 you need to fork the repo and make a pull request on the fork (see readme) :)

Yup, so sorry for not reading that first. Thanks for the pointer!
