### ISSUE TITLE
Adopter: add tooltip to the awaiting data status

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1228]
Create a new adopter account and apply to adopt a pet. You will see that the adoptable pet page will update to tell you the application is submitted, and has a status of `awaiting data`. This is not necessarily intuitive to the user, so please add an icon and tooltip (icon and tooltip should only show if the status is `awaiting_data`). 

Tooltip: 'Please make sure you fill out the adoption questionnaire so staff have enough information to process your application.'

This is not perfect, yet, but we can improve this once we get some users testing it and see what kind of questions we get. I don't want to be too specific because different orgs might handle the questionnaire differently.

See an example of a tooktip in action on our theme here (for password strength): https://geeksui.codescandy.com/geeks/pages/security.html

**Comment by jasonwang7517** [comment]
I can take this as my next issue!

**Comment by kasugaijin** [comment]
@jasonwang7517 all yours!
