### ISSUE TITLE
Top Navbar: Remove the org name on mobile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1236]
The top navbar in mobile does not look great with the logo and name split like this. 

<img width="442" alt="image" src="https://github.com/user-attachments/assets/d0e0dcb9-34b6-40b7-ac78-cdbd1ef04b87">

Please update the navbar to achieve the following: 

- retain the existing behaviour for screen widths where the navbar remains a single row (above ~482px)
- redesign for screens that currently cause it to collapse into two rows (~482px) so that the hamburger and two buttons move to the left, and we show just the logo (no org name) on the right side. This may require a new mobile navbar partial that we show on a certain screen width and below (ideally, stick to the bootstrap breakpoints rather than implement custom CSS)

<img width="320" alt="image" src="https://github.com/user-attachments/assets/f31ce8f9-bc8d-487f-a51e-f548aab7c256">

**Comment by caitlynl22** [comment]
I can take this on.

**Comment by caitlynl22** [comment]
@kasugaijin Is this just for the logged out view? The logged in view actually looks pretty decent.
<img width="414" alt="Screenshot 2024-12-18 at 11 56 28 PM" src="https://github.com/user-attachments/assets/fc41100c-3701-4844-aea4-c44b718e0fd8" />

**Comment by kasugaijin** [comment]
@caitlynl22 i think the logged in view will look different if you add a logo on the organization?
