### ISSUE TITLE
App footer: Update app name

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1260]
Please udate from Open Pet Rescue to Homeward Tails
see the root page `/` footer to recreate

<img width="441" alt="image" src="https://github.com/user-attachments/assets/5480cbcf-fa65-4980-8ea8-5043ebc5c956" />

**Comment by mgrigoriev8109** [comment]
Can I work on this?

**Comment by mgrigoriev8109** [comment]
![image](https://github.com/user-attachments/assets/167f2dc3-ca7a-4826-abd1-f63cbae703d5)
