### ISSUE TITLE
Fosterer Invite: fix input layout

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1288]
For the person details (first name, last name, email, phone), put the input in two columns on 2 rows so the form looks more even (these should stack on smaller screens)

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/50c5e2c2-4657-4b1a-a550-4c99e1f113d9" />

**Comment by edwinthinks** [comment]
I can take this one :)

**Comment by kasugaijin** [comment]
@edwinthinks Christmas commits!

**Comment by edwinthinks** [comment]
Jeje, where can I find this page btw?

**Comment by kasugaijin** [comment]
Log in as staff and go to dashboard > fosterers > invite

**Comment by edwinthinks** [comment]
Got it, and I opened a PR. I took some design liberties here and there.

Taking a look at the app; I'd love to do a design revision on a few spots.

**Comment by kasugaijin** [comment]
@edwinthinks yes please do! Do you want to make a PR for those?
