### ISSUE TITLE
Staff > Pet > Fosters: Add a card for mobile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#1293]
Log in as staff and go to the dashboard > Pet > Fosters tab and make the screen width smaller and you will see the table becomes illegible. Please add cards (check how we do this for the applications tab) for mobile. 

Desktop - good
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/4c7fb778-efe6-4339-9eae-f2e058caf338" />

Mobile - bad
<img width="491" alt="image" src="https://github.com/user-attachments/assets/09ce8ec7-9568-4f7b-a7fb-bc251da6baf5" />

**Comment by jasonwang7517** [comment]
I can take this next!

**Comment by kasugaijin** [comment]
@jasonwang7517 all yours
