### ISSUE TITLE
Fix mobile view for dashboard

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/homeward-tails#218]
Add mobile view for dashboard layout 

Acceptance criteria:
- Menu is collapsed and accessible
- Page content header is collapsed and accessible
- All content is displayed in mobile view

**Comment by reyes-dev** [comment]
I'd like to tackle this one if nobody else has gotten to it yet.

**Comment by avikdal** [comment]
Hi there, I would be happy to take care of this ticket  @nsiwnf
