### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by garyhtou** [rubyforgood/homeward-tails#54]
Let's finish up our deployment setup on Cloud 66

**Comment by Ptrboro** [comment]
**Reminder:** once we have production environment we should reenable strong_migrations gem 🎗️ 
It was disabled in this issue: https://github.com/rubyforgood/pet-rescue/issues/391

**Comment by jmilljr24** [comment]
Deployed to production #1117  and strong_migrations reenabled #883
