### ISSUE TITLE
Fix: Mobile - Staff is not able to use the nav menu on mobile  

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/homeward-tails#545]
Staff is unable to navigate the dashboard on small screens and the hamburger menu does not currently do anything
1. go to [demo site](https://pet-rescue-f6df7ce0e850.herokuapp.com/alta/home)
2. login as staff
    email: [staff@alta.com](mailto:staff@alta.com)
    password: 123456

<img width="300" alt="Screen Shot 2024-03-12 at 10 06 58 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/21acd8ee-0dd6-4b39-957f-50ad0b8c6d1e">

**Comment by kasugaijin** [comment]
FYI this PR made the staff dashboard hamburger funtional https://github.com/rubyforgood/pet-rescue/pull/631
