### ISSUE TITLE
Default Pet Tasks: tasks should be assigned to a general category, or a species

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#709]
Currently default pet tasks are assigned to all new pets, regardless of species. This is not as practical as grouping default pet tasks by species. We can also have a general category, that applies to all species. 

- On the Pet model, add an enum at 0 index `all`
- In the form used to update/create a pet, do not show the `all` option in the select
- Add a new column to the DefaultPetTasks table, `species`, `string`, default `0` (the `all` enum)
- Add this new attribute to the Default Pet task form as a select showing all enums for pet species
- Update the default pet task index table in the UI to show species column
- Organize default pet tasks in the index alphabetically on species
- Update the default pet task service so that when a new pet is created, it's associated tasks will be the tasks with `all` AND the same species as the Pet. E.g., A new dog will get tasks with `all` and `dog` species. 
- Update tests

**Comment by atbalaji** [comment]
Hi @kasugaijin, I have raised 2 PRs . After they are over and merged, i would like to work on this issue

**Comment by kasugaijin** [comment]
@atbalaji once both PRs are merged, if this is still not assigned, for sure! But just in case someone else wants it before then we don't hold issues for people to give a fair chance to all to contribute.

**Comment by atbalaji** [comment]
Hi @kasugaijin , I would like to take this issue up as now both of my PRs are merged

**Comment by kasugaijin** [comment]
@atbalaji all yours

**Comment by atbalaji** [comment]
Just for confirmation @kasugaijin Can you elaborate the first point. U mean to create an enum like named 'species' where 0 represents 'all' option ? That's what u mean ?

**Comment by kasugaijin** [comment]
@atbalaji check the Pet model as there is already an enum. Just need to add an ‘all’ at the zero index of that enum.

**Comment by atbalaji** [comment]
Hi @kasugaijin .I have made changes except for tests part locally. Some differences with the requirement, we shall discuss during PR. But one thing i noticed during the changes is since default pet tasks are not associated with the tasks they create. On deletion of default pet task the corresponding task of a pet is not deleted. Is this the intended behavior?

**Comment by kasugaijin** [comment]
Thanks @atbalaji yes that’s fine. The default pet task is a blueprint for pet tasks but does not need to be associated.

**Comment by kasugaijin** [comment]
Yes for sure you can make a PR without tests and add them later

**Comment by wiliajc87** [comment]
@kasugaijin I was browsing issues and noticed this one--looks like it could be closed since that PR was merged?

**Comment by kasugaijin** [comment]
@wiliajc87 thank you!
