### ISSUE TITLE
Add tests for DefaultPetTask refactor

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#885]
If you look in app/services/organizations we have the DefaultPetTaskService which gets called when we create a new pet, and adds a Task for each DefaultPetTask for that species.
If you look in the Organizations::Staff::PetsController #create you will see we call the service on the new pet

So, to test, we want to

    create the default pet task for dog
    create a dog
    verify that dog has a task with the same name as the default pet task for dogs
    do the same for cat

[PR](https://github.com/rubyforgood/pet-rescue/pull/879)

**Comment by atbalaji** [comment]
Currently I'm not taking this @kasugaijin. I would like to revisit this incase no one else took this.

**Comment by kasugaijin** [comment]
@atbalaji all yours when you want it...just assign yourself.

**Comment by Aaryanpal** [comment]
@kasugaijin can u please assign this

**Comment by kasugaijin** [comment]
@Aaryanpal no need to test front end that looks for DOM elements. Just backend model or controller level makes sense

**Comment by Aaryanpal** [comment]
WIP

**Comment by Aaryanpal** [comment]
WIP

**Comment by Aaryanpal** [comment]
@kasugaijin I am not getting any clue for what use case i need to write the Test Cases.
Any Help Will be Highly Appreciated.

**Comment by kasugaijin** [comment]
@Aaryanpal the original PR added species to the default pet task service, so it would be good to have some tests where we set task A on dogs and task B on cats and make sure they are assigned to cats and dogs when they are created

**Comment by Aaryanpal** [comment]
Thanks for the Guidance @kasugaijin.
Raised the PR

**Comment by jmilljr24** [comment]
@wiliajc87 So PR #879 was merged but we do not have test coverage for it. It added the ability for default pet tasks to be assigns to a general category or by species, ie cat, dog. A new pr for tests was started but was closed before being merged so nothing for testing is done yet.

If you go to the staff dashboard you should see the default pet tasks with the categories. If you create a new pet, the default pet tasks will be added as tasks to this newly created pet.

We want to test that if a default pet task has the category "dog", the newly created dog gets that task. A cat should not get a dog task. 

Let me know if that makes sense and if you would like to be assigned.

**Comment by jmilljr24** [comment]
@wiliajc87 Awesome! Thank you. #1053 is the closed PR that wasn't merge. I might provide more context if you want to take a look.

**Comment by wiliajc87** [comment]
@jmilljr24 Sorry it took so long, but I've got a PR up here now: https://github.com/rubyforgood/homeward-tails/pull/1178/files
