### ISSUE TITLE
Feedback Form: Render it within both dashboard templates instead of redirecting

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#984]
We have the Feedback link in the Staff Dashboard, and the Adopter Foster Dashboard, but this redirects to a new page. Instead, we should render this form within each dashboard layout. You'll probably want two new controllers to handle this. Look at the `Organizations::AdopterFosterer::FaqController` as an example.

**Comment by Aaryanpal** [comment]
@kasugaijin this too

**Comment by kasugaijin** [comment]
@Aaryanpal how's this going?

**Comment by Aaryanpal** [comment]
WIP
@kasugaijin Sorrry for Late Response.
I was out for some work.
Resuming it Now

**Comment by Aaryanpal** [comment]
Hi @kasugaijin,

I'd like to propose a refactoring of our current feedback feature implementation. Here's an overview of the current situation and my proposed changes:

Current Implementation:
- Controller name: `DevContactsController`
- Handles feedback features for both staff and adopters
- Current URL path: `http://localhost:3000/alta/feedback/new`

Proposed Changes:
1. Rename the controller to `FeedbackController` to better reflect its purpose and follow Rails naming conventions
2. Consolidate all feedback-related logic into this single controller
3. Maintain the existing URL structure (`/alta/feedback/new`)

Rationale:
- The current controller name (`dev_contacts_controller`) doesn't clearly communicate its purpose
- After reviewing the codebase, I don't see a compelling reason to maintain separate controllers for staff and adopter feedback

Please let me know your thoughts on this proposed refactoring. I'm happy to provide more detailed implementation plans if needed.

**Comment by kasugaijin** [comment]
Hey @Aaryanpal I appreciate the initiative! I think what you propose makes sense. The ony thing to handle differently if we use a single controller is the layout. I recall the adopter/foster form should be in their dashboard layout.

**Comment by Aaryanpal** [comment]
### For Staff it will look like this
![image](https://github.com/user-attachments/assets/bb734e2b-8cc1-418a-a7d4-a8af85c61882)

### For Adopter it look something like this
![image](https://github.com/user-attachments/assets/c984cc64-e6f7-4b55-b1dc-ffed4e3848d6)

Here's a rephrased version as a message to a dev:

---

I've noticed that the two sections have different styles in the layout. To better align them with the overall design, do you think it would be better to create a separate controller to manage the styles more cleanly? Or should we handle the styling directly within the ERB? Also, do you think it makes sense to adjust the position of the "Feedback" heading to the top-left for better alignment with the design and remove the sub-heading ( `Found a bug? Want to request a feature? Contact our dev team with the form below.`) as we didn't had one in every options?

Let me know your thoughts!

**Comment by kasugaijin** [comment]
> ### For Staff it will look like this
> ![image](https://private-user-images.githubusercontent.com/53212802/374838511-bb734e2b-8cc1-418a-a7d4-a8af85c61882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODMyMTcsIm5iZiI6MTcyODQ4MjkxNywicGF0aCI6Ii81MzIxMjgwMi8zNzQ4Mzg1MTEtYmI3MzRlMmItOGNjMS00MThhLWE3ZDQtYThhZjg1YzYxODgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE0MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNDIwNjMyZjEzYjBhNDVmNjJiZTJlOTIxOTZhNDc2OTkyM2NkNWI3MTA0YmQ4NzIxODEyMDNlYTEyYWE2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iZAocfHJ8vB24WTWb-AZnZ1reGtnp3NLh9zzD6F-yyU)
> 
> ### For Adopter it look something like this
> ![image](https://private-user-images.githubusercontent.com/53212802/374839069-c984cc64-e6f7-4b55-b1dc-ffed4e3848d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODMyMTcsIm5iZiI6MTcyODQ4MjkxNywicGF0aCI6Ii81MzIxMjgwMi8zNzQ4MzkwNjktYzk4NGNjNjQtZTZmNy00YjU1LWIxZGMtZmZlZDRlMzg0OGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE0MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODI2NmZlZjRhZTI4Mzg4ZTI1Njc5YjdkZGYxMDFkYTcxMmEzNWJmY2NjMmYzZjQwMDFlM2QwZjM3YzZiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NGB9jMhFznBtHiS9MIBi-Bz42pc9JQzm905AKfVfkMI)
> 
> Here's a rephrased version as a message to a dev:
> 
> I've noticed that the two sections have different styles in the layout. To better align them with the overall design, do you think it would be better to create a separate controller to manage the styles more cleanly? Or should we handle the styling directly within the ERB? Also, do you think it makes sense to adjust the position of the "Feedback" heading to the top-left for better alignment with the design and remove the sub-heading ( `Found a bug? Want to request a feature? Contact our dev team with the form below.`) as we didn't had one in every options?
> 
> Let me know your thoughts!

Yeah that's what I was thinking in the original issue description - that two controllers would handle this more cleanly. Ideally, we do not have the Feedback Form title in the center on these dashboard scoped pages. The title should live in the header for each dashboard check the other pages under both dashboards to see how their headers are set with breadcrumbs). We should also move the shared components of the page (description and form) into a partial that can be shared between all three views (the form accessed via the footer, the form accessed via the two dashboards).
