### ISSUE TITLE
Custom Page: Add image to page to help user know what form fields relate to what pages

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/homeward-tails#990]
Log in as staff and go to the dashboard > custom page
This form is a little hard to understand for a first time user i.e., which fields update which parts of the website. So adding images will help until we can refactor this design further.

- Please add the assets like below (get them from the custom page section on [Figma](https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=0-1&t=xOV9HtPhr6Okxctg-1)). The assets are in multiple layers e.g., image + text but this would be good to just export as a single layer (screenshot if you must) so it is a single image in each case.
- For mobile, the images should stack below the form. 
- The save button should say 'Save' only

![Image](https://github.com/user-attachments/assets/fae37ee7-9e1a-4f96-9234-ae6dba900203)

**Comment by ErinClaudio** [comment]
Thank you!

**Comment by ErinClaudio** [comment]
@kasugaijin

**Comment by kasugaijin** [comment]
@ErinClaudio yes please, the end result should look something approxmating the image in the description...so you'll be adding the screenshots along with the labels. This helps people see what part of the website the form updates.

**Comment by kasugaijin** [comment]
Can someone please finish this one off? There is a PR here with some progress...not much left to do
https://github.com/rubyforgood/homeward-tails/pull/993
